---
title: "datacleaning"
author: "Lina Elkjær Pedersen"
date: "2023-04-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library("tidyverse")
```

```{r}
df <- read.csv("/Users/linaelkjaerpedersen/Desktop/Datascience/Exam/diabetes_prediction_dataset.csv")


#filter out people of gender "other". There are only 18, and none of them have diabetes. 
df <- df %>% 
  filter(gender != "Other")


#Filter out people who are younger than 2 (or categorize them) 2101 obs, and none of them have diabetes
df <- df %>% 
  filter(age >= 2)

#df <- df %>% 
 #filter(age < 2)

diabetes_df <- df %>% 
  filter(diabetes == 1)


ggplot(df, aes(x = gender, y = diabetes, fill = gender)) +
         geom_count()



#What does "ever" mean????
#df <- df %>% 
  #mutate(smoking = ifelse(smoking_history == "former" | smoking_history == "not current" , "past", smoking_history),
         #)


```

```{r}


#IKKE OPTIMALT SKAL GØRES IKKE AUTOMATISK !
library(dplyr)

#make this example reproducible
set.seed(1)

#adding
df <- mutate(df, id = row_number())

#use 75% of dataset as training set and 25% as test set 
train <- df %>% dplyr::sample_frac(0.75)
test  <- dplyr::anti_join(df, train, by = 'id')



 
```


**Summary stats**
```{r}

df <- read.csv("/Users/linaelkjaerpedersen/Desktop/Datascience/Exam/diabetes_prediction_dataset.csv")

df <- df %>% 
  filter(gender != "Other") %>% 
  mutate(smoking_history = as.factor(smoking_history),
         gender = as.factor(gender), 
         hypertension = as.factor(hypertension),
         heart_disease = as.factor(heart_disease),
         diabetes = as.factor(diabetes))


df_male <- df %>% 
  filter(gender == "Male")

df_female <- df %>% 
  filter(gender == "Female")

summary(df)

sd(df$age)

df_diabetes <- df %>% 
  filter(diabetes == "1")

summary(df_diabetes)
```

